apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: demo-voting-app
    name: result-app-pod

spec:
  replicas: 1
  selector:
    matchlabels:
      app: demo-voting-app
      name: result-app-pod

  template:
    metadata:
      name: result-app-pod
      matchlabels:
        app: demo-voting-app
        name: result-app-pod
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
          ports:
            -containerPort: 80